import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUser,
    faHeart,
    faPlus,
    faTrash,
    faPlusCircle,
    faMusic,
    faEuroSign,
    faSearch,
    faMapMarkerAlt,
    faChevronRight,
    faChevronLeft,
    faLock,
    faComment,
    faCommentAlt,
    faHandSparkles,
    faUserCog,
    faCog,
    faStar,
    faStarHalf,
    faKiwiBird,
    faUsers,
    faTimes,
} from '@fortawesome/free-solid-svg-icons';

import {
    faHeart as farHeart,
    faStar as farStar,
    faImages as farImages
} from '@fortawesome/free-regular-svg-icons';

library.add(
    faEuroSign,
    farHeart,
    farImages,
    faTrash,
    farStar,
    faUser,
    faHeart,
    faPlus,
    faPlusCircle,
    faMusic,
    faSearch,
    faMapMarkerAlt,
    faChevronRight,
    faChevronLeft,
    faLock,
    faComment,
    faCommentAlt,
    faHandSparkles,
    faUserCog,
    faCog,
    faStar,
    faStarHalf,
    faKiwiBird,
    faUsers,
    faTimes,
);