import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faMapMarkerAlt,
    faUser,
    faSearch,
    faChevronRight,
    faChevronLeft,
    faLock,
    faComment,
    faCommentAlt,
    faHandSparkles,
    faUserCog,
    faStar,
    faStarHalf,
    faKiwiBird,
    faUsers,
    faTimes,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faUser,
    faSearch,
    faMapMarkerAlt,
    faChevronRight,
    faChevronLeft,
    faLock,
    faComment,
    faCommentAlt,
    faHandSparkles,
    faUserCog,
    faStar,
    faStarHalf,
    faKiwiBird,
    faUsers,
    faTimes,
);